## Python Basics

In this file you will learn basic datatype and some other important operations used in python. Run cell by cell

In [1]:
# Floats
x = 4.0
y = 2.0

# Addition
print(x + y)

# Subtraction
print(x - y)

# Multiplication
print(x * y)

# Returns the quotient
print(x / y)

# Returns the remainder
print(x % y) 

# Absolute value
print(abs(x))


6.0
2.0
8.0
2.0
0.0
4.0


In [6]:
x = 'Cake'
y = 'Cookie'
x +'&'+ y

'Cake&Cookie'

In [7]:
2*x

'CakeCake'

In [32]:
u= [2*x,2*x]
len(u)

2

In [30]:
# Range Slicing
z1 = len(x)

print(z1)

# Slicing
z2 = y[0] + y[1] 

print(z2)

4
Co


In [42]:
x = '4'
y = '2'

i=(x + y)
print(i)
print(i*2)

42
4242


In [43]:
str.capitalize('cookie')

'Cookie'

In [46]:
s = 'my name is javed ahmad'
print(s)
print(str.capitalize(s))

my name is javed ahmad
My name is javed ahmad


In [47]:
str1 = "Cake 4 U"
str2 = "404"
len(str1)

8

In [48]:
str1.isdigit()

False

In [49]:
str2.isdigit()

True

In [50]:
str1.replace('4 U', str2)

'Cake 404'

In [57]:
str1 = 'may can cook'
str2 = 'cook'
str1.find(str2)

8

In [58]:
x = 4
y = 2
x == y

False

In [59]:
x > y

True

In [64]:
x = 4
y = 2
z = (x==y) # Comparison expression (Evaluates to false)
if z: # Conditional on truth/false value of 'z'
    print("Equal")
else: print("Not Equal")

Not Equal


In [65]:
x = 2
y = 2
z = (x==y) # Comparison expression (Evaluates to false)
if z: # Conditional on truth/false value of 'z'
    print("Equal")
else: print("Not Equal")

Equal


In [68]:
i = 0.4
type(i)

float

In [70]:
x = 2
y = "The Godfather: Part "
fav_movie = (y) + str(x)
print(fav_movie)
print(type(fav_movie))

The Godfather: Part 2
<class 'str'>


In [74]:
import array as arr
a = arr.array("I",[3,6,9])
print(type(a))
a

<class 'array.array'>


array('I', [3, 6, 9])

In [75]:
x = [] # Empty list
type(x)

list

In [76]:
x1 = [1,2,3]
type(x1)

list

In [77]:
x2 = list([1,'apple',3])
type(x2)

list

In [78]:
print(x2[1])

apple


In [88]:
list_num = [1,2,45,6,7,2,90,23,435]
list_char = ['c','o','o','k','i','e']

list_num.append(11) # Add 11 to the list, by default adds to the last position
print(list_num)

[1, 2, 45, 6, 7, 2, 90, 23, 435, 11]


In [89]:
list_num.insert(3, 11)
print(list_num)

[1, 2, 45, 11, 6, 7, 2, 90, 23, 435, 11]


In [90]:
list_char.remove('o') 
print(list_char)

['c', 'o', 'k', 'i', 'e']


In [91]:
list_char.pop(-1) # Removes the item at the specified position
print(list_char)

['c', 'o', 'k', 'i']


In [92]:
list_num.sort() # In-place sorting
print(list_num)

[1, 2, 2, 6, 7, 11, 11, 23, 45, 90, 435]


In [93]:
list.reverse(list_num)
print(list_num)

[435, 90, 45, 23, 11, 11, 7, 6, 2, 2, 1]


In [94]:
import numpy as np

arr_a = np.array([3, 6, 9])
arr_b = arr_a/3 # Performing vectorized (element-wise) operations 
print(arr_b)

[1. 2. 3.]


In [95]:
arr_ones = np.ones(4)
print(arr_ones)

[1. 1. 1. 1.]


In [96]:
multi_arr_ones = np.ones((3,4)) # Creating 2D array with 3 rows and 4 columns
print(multi_arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [97]:
graph = { "a" : ["c", "d"],
          "b" : ["d", "e"],
          "c" : ["a", "e"],
          "d" : ["a", "b"],
          "e" : ["b", "c"]
        }

def define_edges(graph):
    edges = []
    for vertices in graph:
        for neighbour in graph[vertices]:
            edges.append((vertices, neighbour))
    return edges

print(define_edges(graph))

[('a', 'c'), ('a', 'd'), ('b', 'd'), ('b', 'e'), ('c', 'a'), ('c', 'e'), ('d', 'a'), ('d', 'b'), ('e', 'b'), ('e', 'c')]


In [98]:
class Tree:
    def __init__(self, info, left=None, right=None):
        self.info = info
        self.left  = left
        self.right = right

    def __str__(self):
        return (str(self.info) + ', Left child: ' + str(self.left) + ', Right child: ' + str(self.right))

tree = Tree(1, Tree(2, 2.1, 2.2), Tree(3, 3.1))
print(tree)

1, Left child: 2, Left child: 2.1, Right child: 2.2, Right child: 3, Left child: 3.1, Right child: None


In [99]:
x_dict = {'Edward':1, 'Jorge':2, 'Prem':3, 'Joe':4}
del x_dict['Joe']
x_dict

{'Edward': 1, 'Jorge': 2, 'Prem': 3}

In [104]:
x_dict['Edward']

1

In [105]:
len(x_dict)

3

In [106]:
x_dict.keys()

dict_keys(['Edward', 'Jorge', 'Prem'])

In [108]:
x_dict.values()

dict_values([1, 2, 3])

In [112]:
x_set = set('CAKE&COKE')
y_set = set('COOKIE')

print(x_set)
print(y_set)

{'E', 'K', 'O', 'C', '&', 'A'}
{'O', 'E', 'K', 'C', 'I'}


In [113]:
print(x_set - y_set) # All the elements in x_set but not in y_set

{'A', '&'}


In [114]:
print(x_set|y_set) # Unique elements in x_set or y_set or both

{'E', 'K', 'O', 'C', '&', 'I', 'A'}


In [115]:
print(x_set & y_set) # Elements in both x_set and y_set

{'O', 'C', 'E', 'K'}
